### ISSUE TITLE
some UI broken

### ISSUE THREAD

**Issue by jtydhr88** [jtydhr88/sd-canvas-editor#13]
in order to fix https://github.com/jtydhr88/sd-canvas-editor/issues/12, some new UI issues are introduced
![image](https://user-images.githubusercontent.com/860985/235694439-5d794264-8cdd-421e-bdb8-d5a179a6a8fe.png)
![image](https://user-images.githubusercontent.com/860985/235694515-bffea54a-f6eb-4eda-b65d-0353c333dc9a.png)
need to deal with them later

**Comment by AGronowski** [comment]
also for me now it takes a few seconds for the canvas editor to load, before you didn't have to wait
