### ISSUE TITLE
This extension is always communicating with "api.polotno.dev" and thus requires internet connection to run locally

### ISSUE THREAD

**Issue by ye7iaserag** [jtydhr88/sd-canvas-editor#16]
Basically title, webui is designed to run fully local, why is the extension fetching js files from polotno.dev which in turn does http requests to api.polotno.dev?

**Comment by jtydhr88** [comment]
No special reason, I just follow the framework document which required api key, see https://polotno.com/docs/overview, I think the Polotno needs check the api key is valid.
Here is the Polotno project official GitHub https://github.com/polotno-project/polotno-studio, please open its issue and I think it is the best place to get answer which your concern.
 I will close this issue for now.
